### PR TITLE
fix: do not delete a server channels when deleting server from collection

### PR DESCRIPTION
**Pull request by amycatgirl**
## Please make sure to check the following tasks before opening and submitting a PR

- [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/.github/blob/master/.github/CONTRIBUTING.md)
- [x] I have tested my changes locally and they are working as intended

### CODE REVIEW

**Comment by amycatgirl** [comment]
i am not getting those minutes of my life back

**Comment by DeclanChidlow** [comment]
@insertish Bump on this as it seems to be impacting AutoMod.

**Comment by insertish** [comment]
Not sure what's going on with the lockfile here? I think I can just remove it in the PR.

Also, this isn't an ideal solution but I suppose server deletes/leaves are uncommon.

**Comment by insertish** [comment]
Are there some reference errors?
Just want to see if there are any other options.

**Comment by DeclanChidlow** [comment]
https://github.com/revoltchat/revolt.js/issues/96

**Comment by insertish** [comment]
I'll continue discussing there.

**Pull request closed without merging**
